import { useMemo, useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { useOrders } from "@/context/OrdersContext";
import { useAuth } from "@/context/AuthContext";
import { ClipboardList, Printer, Calendar } from "lucide-react";

const ZReading = () => {
  const { orders } = useOrders();
  const { user } = useAuth();
  const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10));

  const data = useMemo(() => {
    const day = new Date(date);
    const dayStr = day.toDateString();
    const todays = orders.filter((o) => new Date(o.date).toDateString() === dayStr);
    const valid = todays.filter((o) => !o.voided);
    const voided = todays.filter((o) => o.voided);

    const gross = valid.reduce((s, o) => s + o.total, 0);
    const discounts = valid.reduce((s, o) => s + (o.discountAmount || 0), 0);
    const vat = valid.reduce((s, o) => s + (o.vat || 0), 0);
    const itemsSold = valid.reduce((s, o) => s + o.items.reduce((a, i) => a + i.quantity, 0), 0);

    const byPayment = valid.reduce((acc, o) => {
      const m = o.paymentMethod || "Cash";
      acc[m] = (acc[m] || 0) + o.total;
      return acc;
    }, {} as Record<string, number>);

    const byCashier = valid.reduce((acc, o) => {
      acc[o.cashier] = (acc[o.cashier] || 0) + o.total;
      return acc;
    }, {} as Record<string, number>);

    const firstId = valid.length ? Math.min(...valid.map((o) => o.id)) : null;
    const lastId = valid.length ? Math.max(...valid.map((o) => o.id)) : null;

    return { todays, valid, voided, gross, discounts, vat, itemsSold, byPayment, byCashier, firstId, lastId };
  }, [orders, date]);

  const print = () => window.print();

  return (
    <div className="p-4 md:p-8 max-w-3xl mx-auto space-y-6">
      <header className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold flex items-center gap-2">
            <ClipboardList className="h-7 w-7 text-primary" /> Daily Z-Reading
          </h1>
          <p className="text-sm text-muted-foreground">End-of-day sales summary report</p>
        </div>
        <div className="flex items-end gap-2">
          <div>
            <Label className="text-xs text-muted-foreground flex items-center gap-1"><Calendar className="h-3 w-3" /> Date</Label>
            <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="h-9" />
          </div>
          <Button onClick={print}><Printer className="h-4 w-4" /> Print</Button>
        </div>
      </header>

      <Card className="p-6 md:p-8 print:shadow-none print:border-0">
        <div className="text-center border-b pb-4 mb-4">
          <h2 className="text-xl font-bold">Z-READING REPORT</h2>
          <p className="text-sm text-muted-foreground">Sari-Sari Mart · 123 Rizal St., Manila</p>
          <p className="text-sm font-medium mt-2">{new Date(date).toLocaleDateString(undefined, { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</p>
          <p className="text-xs text-muted-foreground">Generated by {user?.name} · {new Date().toLocaleString()}</p>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-6">
          <Card className="p-4">
            <p className="text-xs text-muted-foreground">Total Transactions</p>
            <p className="text-2xl font-bold">{data.valid.length}</p>
            {data.voided.length > 0 && <p className="text-xs text-destructive">{data.voided.length} voided</p>}
          </Card>
          <Card className="p-4">
            <p className="text-xs text-muted-foreground">Items Sold</p>
            <p className="text-2xl font-bold">{data.itemsSold}</p>
          </Card>
          <Card className="p-4 col-span-2 bg-[image:var(--gradient-primary)] text-primary-foreground">
            <p className="text-xs opacity-80">Gross Sales</p>
            <p className="text-3xl font-bold">₱{data.gross.toFixed(2)}</p>
          </Card>
        </div>

        <div className="space-y-2 text-sm border-t pt-4">
          <Row label="Total Discounts" value={`−₱${data.discounts.toFixed(2)}`} />
          <Row label="VAT (12%)" value={`₱${data.vat.toFixed(2)}`} />
          <Row label="First Receipt #" value={data.firstId ? `#${data.firstId}` : "—"} />
          <Row label="Last Receipt #" value={data.lastId ? `#${data.lastId}` : "—"} />
        </div>

        <div className="border-t mt-4 pt-4">
          <h3 className="font-semibold text-sm mb-2">Sales by Payment Method</h3>
          {Object.keys(data.byPayment).length === 0 ? (
            <p className="text-sm text-muted-foreground">No sales today.</p>
          ) : (
            Object.entries(data.byPayment).map(([m, v]) => (
              <Row key={m} label={m} value={`₱${v.toFixed(2)}`} />
            ))
          )}
        </div>

        <div className="border-t mt-4 pt-4">
          <h3 className="font-semibold text-sm mb-2">Sales by Cashier</h3>
          {Object.keys(data.byCashier).length === 0 ? (
            <p className="text-sm text-muted-foreground">No sales today.</p>
          ) : (
            Object.entries(data.byCashier).map(([c, v]) => (
              <Row key={c} label={c} value={`₱${v.toFixed(2)}`} />
            ))
          )}
        </div>

        {data.voided.length > 0 && (
          <div className="border-t mt-4 pt-4">
            <h3 className="font-semibold text-sm mb-2">Voided Transactions</h3>
            {data.voided.map((o) => (
              <div key={o.id} className="flex justify-between text-sm py-1">
                <span>#{o.id} <Badge variant="destructive" className="text-[10px] ml-1">VOID</Badge></span>
                <span className="text-muted-foreground line-through">₱{o.total.toFixed(2)}</span>
              </div>
            ))}
          </div>
        )}

        <div className="border-t mt-6 pt-4 text-center text-xs text-muted-foreground">
          *** END OF DAY REPORT ***
        </div>
      </Card>
    </div>
  );
};

const Row = ({ label, value }: { label: string; value: string }) => (
  <div className="flex justify-between">
    <span className="text-muted-foreground">{label}</span>
    <span className="font-semibold">{value}</span>
  </div>
);

export default ZReading;
